vault:
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_ROLE: "argocd"
  AVP_TYPE: "vault"
  VAULT_ADDR: "http://vault.default.svc:8200"

argo-cd:

  ## Repo Server
  repoServer:      
    # -- The number of repo server pods to run
    replicas: 1

    autoscaling:
      # -- Enable Horizontal Pod Autoscaler ([HPA]) for the repo server
      enabled: false

    ## Repo server metrics service configuration
    metrics:
      # -- Deploy metrics service
      enabled: false   
      serviceMonitor:
        # -- Enable a prometheus ServiceMonitor
        enabled: false
        

  server:     
    # -- The number of server pods to run
    replicas: 1

    autoscaling:
      # -- Enable Horizontal Pod Autoscaler ([HPA]) for the Argo CD server
      enabled: false
      
    ## Server metrics service configuration
    metrics:
      # -- Deploy metrics service
      enabled: false

      serviceMonitor:
        # -- Enable a prometheus ServiceMonitor
        enabled: false   
