kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  AVP_AUTH_TYPE: {{ .Values.vault.AVP_AUTH_TYPE }}
  AVP_K8S_ROLE: {{ .Values.vault.AVP_K8S_ROLE }}
  AVP_TYPE: {{ .Values.vault.AVP_TYPE }}
  VAULT_ADDR: {{ .Values.vault.VAULT_ADDR }}
